### ISSUE TITLE
Footprint changes when list of things is not in same order

### ISSUE THREAD

**Issue by ryanzbone** [covermymeds/sql_footprint#18]
-TRUNCATE TABLE "public"."queue_items", "public"."notes", "public"."sessions", "public"."incoming_faxes", "public"."outbound_faxes", "public"."users", "public"."status_histories", "public"."fax_poller_results" RESTART IDENTITY CASCADE;
+TRUNCATE TABLE "public"."queue_items", "public"."notes", "public"."sessions", "public"."fax_poller_results", "public"."users", "public"."status_histories", "public"."incoming_faxes", "public"."outbound_faxes" RESTART IDENTITY CASCADE;

also
![screen shot 2016-04-26 at 2 42 53 pm](https://cloud.githubusercontent.com/assets/2286261/14830165/34e5e5f4-0bbd-11e6-9c53-7f9a5fedd065.png)

**Comment by brandonjoyce** [comment]
Hmm.. that could be a tough one.  Do you know what's causing the fields to be in a different order?  It doesn't seem like an important distinction, but I'm not quite sure how to dedupe that one.  Anyone have an idea?

I suppose we could make a special case for TRUNCATE TABLE where it splits on whitespace and sorts the table names alphabetically.

**Comment by ryanzbone** [comment]
I don't know why they end up in different orders, but I figured we could do exactly what you said, a special case for truncate table where we sort the things.

**Comment by mikegee** [comment]
I sincerely doubt your application truncates all the tables. Sounds like something your specs would do.

Find the culprit (I suspect DatabaseCleaner) and wrap it with `SqlFootprint.exclude {}`.

**Comment by schneiderderek** [comment]
I think we should save special cases as a last resort. It would be nice to dig into whatever is causing this and understand if it's a TRUNCATE specific thing, or if we could expect something similar with any SQL statements. 

If this is truncating tables then I doubt this is 'real' code running. Also, I would be surprised if your creating table triggers in your 'real' code. I'm assuming this is some test setup that is running, which should be excluded from your SQL footprint. Let me know if I'm wrong here.
l

**Comment by schneiderderek** [comment]
Looks like mike beat me to it.

**Comment by ryanzbone** [comment]
>I doubt your application truncates all the tables.

A fine point indeed. Wrapping up my database cleaner logic clears this up.
